apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform-level project for bootstrap and generated applications
  sourceRepos:
    - https://github.com/geekahmed-yt/hello-argocd-bootstrap.git
    - https://github.com/*/hello*manifests.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
